theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "北辕记"
description: "施工中，测试"

show_downloads: "false"
# google_analytics: ?
